﻿using Dumptruck.Lua;
using QuestMaster.LuaParser;
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;

namespace QuestMaster.LuaParser
{
    public class LuaGameObject
    {
        public int Id;

        public LuaGameObject(int targetId)
        {
            Id = targetId;
        }
        
        public int GetLayoutId()
        {
            return Id;
        }

        public int GetBaseId()
        {
            return Id;
        }
        
        public int GetQuestSequence(int QuestId)
        {
            return Id;
        }

        public bool IsDying()
        {
            LastField = GetCurrentMethod(0);
            return true;
        }

        public Tuple<QuestStateFunc, int> LastField = null; 


        public dynamic GetNumOfItems(int item, byte filter, bool unka, bool unkb, params int[] args)
        {
            //dynamic MyDynamic = new System.Dynamic.ExpandoObject();
            //MyDynamic.Item = item;
            //MyDynamic.Filter = (ItemFilter)filter;
            //return MyDynamic;
            var res = new GetNumOfItems
            {
                filter = (ItemFilter)filter,
                ItemId = item,
                UnkA = unka,
                UnkB = unkb,
                Args = args,

            };
            return res;
        }

        public int GetNeedDailySupplyPoint()
        {
            return -1;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public Tuple<QuestStateFunc, int> GetCurrentMethod(int p)
        {
            StackTrace st = new StackTrace();
            StackFrame sf = st.GetFrame(1);

            return new Tuple<QuestStateFunc, int>((QuestStateFunc)Enum.Parse(typeof(QuestStateFunc), sf.GetMethod().Name), p);
        }

        #region AutoGenerated GetTodo
        public int GetQuestI8A(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI8B(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI8C(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI8D(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI8E(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI8F(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8A(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8B(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8C(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8D(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8E(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8F(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8AH(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8BH(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8CH(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8DH(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8EH(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8FH(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8AL(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8BL(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8CL(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8DL(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8EL(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI8FL(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI16A(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI16B(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI16C(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI16A(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI16B(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI16C(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestI32A(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestUI32A(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public int GetQuestBranch(int QuestId)
        {
            LastField = GetCurrentMethod(0);
            return 0;
        }

        public bool GetQuestBitFlag8(int QuestId, int param)
        {
            LastField = GetCurrentMethod(param);
            return false;
        }

        public bool GetQuestBitFlag16(int QuestId, int param)
        {
            LastField = GetCurrentMethod(param);
            return false;
        }

        public bool GetQuestBitFlag24(int QuestId, int param)
        {
            LastField = GetCurrentMethod(param);
            return false;
        }

        public bool GetQuestBitFlag32(int QuestId, int param)
        {
            LastField = GetCurrentMethod(param);
            return false;
        }

        public bool GetQuestBitFlag40(int QuestId, int param)
        {
            LastField = GetCurrentMethod(param);
            return false;
        }

        public bool GetQuestBitFlag48(int QuestId, int param)
        {
            LastField = GetCurrentMethod(param);
            return false;
        }


        #endregion
    }
}
